### ISSUE TITLE
Exosama & EVMOS support

### ISSUE THREAD

**Issue by BrickheadJohnny** [agoraxyz/guild.xyz#703]
```[tasklist]
### Todo
- [ ] Add Exosama chain
- [ ] Add EVMOS chain
- [ ] Simplify `connectors.ts` (or at least add proper types to it) so we can add new supported chains more quickly in the future
```
