### ISSUE TITLE
PostHog event tracking & A/B testing

### ISSUE THREAD

**Issue by BrickheadJohnny** [agoraxyz/guild.xyz#716]
```[tasklist]
### Tasks
- [x] Add PostHog to Guild.xyz ([example](https://github.com/PostHog/posthog-js/tree/master/playground/nextjs))
- [x] Migrate Guild Checkout related events from Datadog to PostHog
- [ ] Implement A/B tests for the Arbitrum guild
```

**Comment by hamzaXRM** [comment]
lkhujl
